import 'app_state.dart';

// ╔══════════════════════════════════════════════════════════════════════╗
// ║  AppLocalizations — TR / EN string maps for the Duck app            ║
// ╚══════════════════════════════════════════════════════════════════════╝

/// Usage:  `S.get('settings')`  or  `S.get('lesson_n', args: {'n': '5'})`
class S {
  S._();

  /// Returns the localised string for [key].
  /// Optional [args] map replaces `{key}` placeholders in the result.
  static String get(String key, {Map<String, String>? args}) {
    final locale = AppState.instance.locale;
    String value = (_translations[locale] ?? _translations['tr']!)[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  // ────────────────────────────────────────────────────────────────────
  //  TRANSLATION MAP
  // ────────────────────────────────────────────────────────────────────
  static final Map<String, Map<String, String>> _translations = {
    // ═══════════════════  TURKISH  ════════════════════════════════════
    'tr': {
      // ── Common ───────────────────────────────────────
      'app_name': 'Duck',
      'continue_btn': 'Devam Et',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'close': 'Kapat',
      'back': 'Geri Dön',
      'start': 'Başla',
      'retry': 'Tekrar Dene',
      'done': 'Tamam',
      'yes': 'Evet',
      'no': 'Hayır',
      'ok': 'Tamam',
      'exit': 'Çıkış',
      'exit_btn': 'Çık',
      'correct': 'Doğru',
      'wrong': 'Yanlış',
      'score': 'Puan',
      'time': 'Süre',
      'level': 'Seviye',
      'success': 'Başarı',
      'lesson': 'Ders',
      'completed': 'Tamamlandı',
      'play_again': 'Tekrar Oyna',
      'main_menu': 'Ana Menü',
      'continue_playing': 'Devam Et',
      'unknown_error': 'Bilinmeyen hata',

      // ── Splash ───────────────────────────────────────
      'splash_hello': 'Merhaba',
      'splash_iam_duck': 'Ben Duck',
      'splash_assistant': 'Senin sanal İngilizce asistanınım',
      'splash_preparing': 'Hazırlanıyor...',
      'splash_easy': 'Duck ile İngilizce öğrenmek çok kolay',

      // ── Onboarding ──────────────────────────────────
      'onboard_hello': 'Merhaba! Ben Duck 🦆',
      'onboard_assistant': 'Senin sanal İngilizce asistanınım ✨',
      'onboard_ask_name': 'Sana nasıl hitap etmemi istersin?',
      'onboard_welcome': 'Hoşgeldin {name}!',
      'onboard_name_hint': 'İsmini yaz...',
      'onboard_name_note': 'Duck sana bu şekilde hitap edecek.',
      'onboard_continue': 'Devam Et',
      'onboard_lets_start': 'O zaman başlayalım',
      'onboard_great_journey': 'Harika bir yolculuğa başlıyoruz!',
      'onboard_placement_test': 'Seviye Tespit Sınavı',
      'onboard_know_my_level': 'Seviyemi Biliyorum',

      // ── Select Level ────────────────────────────────
      'select_where': 'Nereden başlamak istersin?',
      'select_subtitle': 'Seviyeni seç ve öğrenmeye başla',
      'select_start': 'Başlayalım!',
      'select_pick': 'Bir seviye seç',
      'level_beginner': 'Başlangıç',
      'level_beginner_desc': 'Temel kelimeler ve basit cümleler',
      'level_elementary': 'Temel',
      'level_elementary_desc': 'Günlük konuşmalar ve basit diyaloglar',
      'level_intermediate': 'Orta Seviye',
      'level_intermediate_desc': 'Akıcı iletişim ve detaylı konular',
      'level_upper_intermediate': 'Orta Üstü',
      'level_upper_intermediate_desc': 'Karmaşık konular',
      'level_advanced': 'İleri Seviye',
      'level_advanced_desc': 'Akademik ve profesyonel düzey',

      // ── Home Screen ─────────────────────────────────
      'home_welcome': 'Hoşgeldin',
      'home_default_user': 'Kullanıcı',
      'home_learn_english': '🦆 İngilizce Öğren',
      'home_daily_goals': 'Günlük Hedefler',
      'home_quick_start': 'Hızlı Başla',
      'home_pick_level': 'Seviyeni Seç',
      'home_25_lessons': 'Her seviyede 25 ders var',
      'home_25_lessons_short': '25 ders',
      'home_beginner': 'Başlangıç',
      'home_beginner_desc': 'Temel kelimeler ve cümleler',
      'home_elementary': 'Temel',
      'home_elementary_desc': 'Günlük konuşmalar',
      'home_intermediate': 'Orta',
      'home_intermediate_desc': 'Akıcı iletişim',
      'home_upper_intermediate': 'Orta Üstü',
      'home_upper_intermediate_desc': 'Karmaşık konular',
      'home_advanced': 'İleri',
      'home_advanced_desc': 'Profesyonel düzey',
      'home_completed': 'Tamamlandı',
      'home_continue': 'Devam Et',
      'home_level_n': 'Seviye {level}',
      'home_lesson_n': 'Ders {n}',
      'home_lesson_progress': '{completed} / 25 ders · %{percent}',
      'home_continue_where': 'Kaldığın yerden devam et',
      'home_level_lesson': 'Seviye {level} - Ders {n}',
      'home_level_complete': 'Seviye {level} Tamamlandı! 🎉',
      'home_day_streak': 'Gün Serisi',
      'home_lessons': 'Dersler',
      'home_total_xp': 'Toplam XP',
      'home_vocabulary': 'Kelime',
      'home_vocabulary_desc': 'Yeni kelimeler öğren',
      'home_listening': 'Dinleme',
      'home_listening_desc': 'Kulağını geliştir',
      'home_mini_games': 'Mini Oyunlar',
      'home_fast_word': 'Hızlı Kelime',
      'home_fast_word_desc': 'En hızlı şekilde cevapla!',
      'home_true_false': 'Doğru Yanlış',
      'home_true_false_desc': 'Bilgini test et!',
      'home_word_match': 'Kelime Eşleştirmece',
      'home_word_match_desc': 'Hafıza oyunu ile öğren!',
      'home_daily_quests': 'Günlük Görevler',
      'home_weekly_quests': 'Haftalık Görevler',
      'home_quest_done': 'Tamamlandı!',
      'home_collect': 'Topla',
      'home_coming_soon': 'Yakında',
      'home_xp_earned': '🎉 +{xp} XP kazandınız!',
      'home_xp_level_up': '🎉 +{xp} XP kazandınız!\n🌟 Seviye Atladınız!',
      'home_achievements': 'Başarıların',
      'home_tab_learn': 'Öğren',
      'home_tab_games': 'Oyunlar',
      'home_tab_quests': 'Görevler',
      'home_tab_achievements': 'Başarılar',
      'home_multiple_choice': 'Çoktan Seçmeli',
      'home_fill_blank': 'Boşluk Doldurma',
      'home_word_order': 'Kelime Sıralama',
      'home_translation': 'Çeviri',
      'home_speaking': 'Konuşma',
      'home_matching': 'Eşleştirme',
      'home_lesson_detail': '{level} · Ders {n}',
      'home_lesson_done_msg': 'Tamamlandı ✅ Tekrar çözebilirsin!',
      'home_lesson_start_msg': 'Bu dersi tamamla ve XP kazan!',
      'home_activities': '{n} Etkinlik',
      'home_redo': 'Tekrar Çöz',
      'home_start_lesson': 'Derse Başla',

      // ── Exercise Screen ─────────────────────────────
      'ex_multiple_choice': 'Çoktan Seçmeli',
      'ex_fill_blank': 'Boşluk Doldurma',
      'ex_word_order': 'Kelime Sıralama',
      'ex_speaking': 'Konuşma',
      'ex_translation': 'Çeviri',
      'ex_matching': 'Eşleştirme',
      'ex_exercise': 'Egzersiz',
      'ex_not_found': 'Ders içeriği bulunamadı (ID: {id})',
      'ex_preparing': 'Bu ders için henüz egzersiz hazırlanıyor.',
      'ex_load_error': 'Egzersiz yüklenirken hata oluştu: {e}',
      'ex_great': 'Harika!',
      'ex_great_desc': 'Çok başarılı bir ders tamamladın!',
      'ex_more_practice': 'Biraz daha pratik yaparak mükemmel olabilirsin.',
      'ex_keep_going': 'Devam Et!',
      'ex_review_topic': 'Konuyu tekrar gözden geçirmeyi dene.',
      'ex_try_again_improve': 'Tekrar deneyerek gelişebilirsin.',
      'ex_lesson_complete': 'Ders Tamamlandı',
      'ex_success': 'Başarı',
      'ex_correct': 'Doğru',
      'ex_wrong': 'Yanlış',
      'ex_best_streak': 'En İyi Seri',
      'ex_review_needed': 'Tekrar Etmen Gerekenler',
      'ex_n_questions': '{n} soru',
      'ex_correct_answer': 'Doğru cevap:',
      'ex_continue': 'DEVAM ET',
      'ex_loading': 'Egzersizler hazırlanıyor...',
      'ex_back': 'Geri Dön',
      'ex_results': 'Sonuçlar',
      'ex_quit_title': 'Çıkmak istiyor musun?',
      'ex_quit_message': 'İlerlemen kaydedilmeyecek.',
      'ex_streak_2': 'İki doğru üst üste! 🔥',
      'ex_streak_3': 'Üç doğru seri! 🔥🔥',
      'ex_streak_4': 'Süper seri! 🔥🔥🔥',
      'ex_perfect': 'Mükemmel! 🎉',
      'ex_awesome': 'Harika! 🎉',
      'ex_correct_answer_msg': 'Doğru cevap!',
      'ex_wrong_answer_msg': 'Yanlış cevap 😕',
      'ex_wrong_feedback': 'Tekrar deneyebilir veya doğru cevabı görebilirsin.',
      'ex_retry': 'Tekrar Dene',
      'ex_show_answer': 'Cevabı Gör',
      'ex_unknown_type': 'Bilinmeyen egzersiz tipi: {type}',
      'ex_render_error': 'Egzersiz görüntülenirken hata oluştu',
      'ex_magnificent': 'Muhteşem!',
      'ex_near_perfect': 'Neredeyse kusursuz bir performans!',
      'ex_doing_well': 'İyi Gidiyorsun!',
      'ex_dont_give_up': 'Pes Etme!',
      'ex_unstoppable': 'Durdurulamıyorsun! ⚡',
      'ex_match_progress': '{matched} / {total} eşleşme',
      'ex_match_hint': 'Sol ve sağdan birer kart seç',
      'ex_translate_hint': 'Çevirinizi yazın...',
      'ex_speak_hint': 'Konuşmak için mikrofona bas',

      // ── Placement Test ──────────────────────────────
      'pt_title': 'Seviye Tespit Sınavı',
      'pt_subtitle': 'İngilizce seviyeni belirleyelim',
      'pt_50_questions': '50 Soru',
      'pt_50_desc': 'Farklı zorluk seviyelerinde sorular',
      'pt_30_min': '30 Dakika',
      'pt_determine': 'Seviye Belirleme',
      'pt_start': 'Sınava Başla',
      'pt_back': 'Geri Dön',
      'pt_select_error': 'Test soruları seçilemedi',
      'pt_load_error': 'Sorular yüklenirken hata: {e}',
      'pt_loading': 'Sorular Hazırlanıyor...',
      'pt_load_fail': 'Sorular Yüklenemedi',
      'pt_retry': 'Tekrar Dene',
      'pt_question_n': 'Soru {n}',
      'pt_answered': '{n} cevaplandı',
      'pt_points': '{n} puan',
      'pt_finish': 'Sınavı Bitir',
      'pt_next': 'Sonraki',
      'pt_congrats': 'Tebrikler!',
      'pt_complete': 'Seviye testin tamamlandı',
      'pt_total_score': 'Toplam Puan',
      'pt_correct_answers': 'Doğru Cevap',
      'pt_success_rate': 'Başarı Oranı',
      'pt_your_level': 'Senin Seviyen: {level}',
      'pt_exit_title': 'Sınavdan Çık',
      'pt_exit_msg': 'Sınavdan çıkarsan tüm ilerleme kaybedilecek. Emin misin?',
      'pt_beginner': 'Başlangıç Seviyesi',
      'pt_elementary': 'Temel Seviye',
      'pt_intermediate': 'Orta Seviye',
      'pt_upper_intermediate': 'Orta Üstü Seviye',
      'pt_advanced': 'İleri Seviye',
      'pt_test': 'Seviye Testi',
      'pt_questions_fail': 'Sorular yüklenemedi',
      'pt_previous': 'Önceki',
      'pt_elapsed': 'Geçen Süre',
      'pt_max_time': 'Maksimum süre sınırı',
      'pt_assessment_desc': 'A1\'den C1\'e kadar değerlendirme',

      // ── Learning Path ───────────────────────────────
      'lp_title': 'Öğrenme Patikası',
      'lp_subtitle': 'Seviyeni geliştir',
      'lp_active_level': 'Aktif Seviye',
      'lp_level_status': 'Seviye Durumu',
      'lp_completed': 'Tamamlandı',
      'lp_completed_check': 'Tamamlandı ✓',
      'lp_lesson_progress': 'Ders {p} / {total}',
      'lp_level_progress': '{level} · Tamamlandı',
      'lp_level_in_progress': '{level} · Ders {p} / {total}',
      'lp_level_n': 'Seviye {level}',
      'lp_lessons_status': '{total} ders · {status}',
      'lp_lesson_n': 'Ders {n}',
      'lp_close': 'Kapat',
      'lp_redo': 'Tekrar Yap',
      'lp_start': 'Başla',
      'lp_congrats': '🎉 Tebrikler! 🎉',
      'lp_level_done': '{level} seviyesini başarıyla tamamladın!',
      'lp_next_level': 'Bir sonraki seviyeye geçtin!',
      'lp_next_lesson': 'Ders 1 / {total} seni bekliyor',
      'lp_all_done': 'Tüm seviyeleri tamamladın! Artık uzman modundasın.',
      'lp_go_next': 'Bir sonraki seviyeye geç',
      'lp_awesome': 'Harika!',
      'lp_locked': 'Kilitli',
      'lp_locked_emoji': 'Kilitli 🔒',

      // ── Vocabulary ──────────────────────────────────
      'vocab_title': 'Kelime Öğren',
      'vocab_level': 'Seviye: {level}',
      'vocab_tap_hint': 'Ekrana dokun, sonraki kelimeye geç',
      'vocab_learn_desc': 'İngilizce - Türkçe kelimeleri öğren',
      'vocab_start': 'Başla',
      'vocab_turkish': '🇹🇷 Türkçe',
      'vocab_next_hint': 'Sonraki kelime için dokun',

      // ── Settings ────────────────────────────────────
      'settings_title': 'Ayarlar',
      'settings_preferences': 'Tercihler',
      'settings_appearance': 'Görünüm',
      'settings_language': 'Dil',
      'settings_about': 'Hakkında',
      'settings_notifications': 'Bildirimler',
      'settings_notifications_desc': 'Hatırlatıcılar ve güncellemeler',
      'settings_vibration': 'Titreşim',
      'settings_vibration_desc': 'Dokunmatik geri bildirim',
      'settings_theme': 'Tema',
      'settings_theme_light': 'Açık',
      'settings_theme_dark': 'Koyu',
      'settings_app_language': 'Uygulama Dili',
      'settings_premium': 'Premium Üye',
      'settings_name_changes': 'İsim değişikliği: {n}/2 hak kaldı',
      'settings_edit_name': 'İsim Düzenle',
      'settings_new_name_hint': 'Yeni isminizi girin',
      'settings_name_changes_left': '{n} değişiklik hakkınız kaldı',
      'settings_name_updated': 'İsminiz "{name}" olarak güncellendi!',
      'settings_name_limit': 'Bu ay için isim değiştirme hakkınız kalmadı.',
      'settings_logout': 'Çıkış Yap',
      'settings_logout_msg':
          'Çıkış yapmak istediğinize emin misiniz? Tüm verileriniz silinecektir.',
      'settings_developer': 'Geliştirici',
      'settings_app_desc': 'İngilizce Öğrenme Uygulaması',
      'settings_terms': 'Kullanım Koşulları',
      'settings_privacy': 'Gizlilik Politikası',
      'settings_kvkk': 'KVKK Aydınlatma Metni',
      'settings_licenses': 'Açık Kaynak Lisansları',
      'settings_last_update': 'Son güncelleme: 1 Ocak 2025',

      // ── Games — Fast Word ───────────────────────────
      'fw_question_n': 'Soru {n}/{total}',
      'fw_loading': 'Hızlı Kelime oyunu hazırlanıyor...',
      'fw_instruction': 'En hızlı şekilde doğru cevabı bul!',
      'fw_correct': 'Doğru',
      'fw_wrong': 'Yanlış',
      'fw_time': 'Süre',
      'fw_perfect': 'Mükemmel!',
      'fw_great': 'Harika!',
      'fw_good': 'İyi!',
      'fw_practice': 'Pratik Yap!',
      'fw_game_over': 'Hızlı Kelime - Oyun Bitti!',
      'fw_total_score': 'TOPLAM SKOR',
      'fw_fast_tip': 'Hızlı cevaplar daha çok puan kazandırır!',
      'fw_success': 'Başarı',
      'fw_level': 'Seviye',
      'fw_exit_title': 'Oyundan Çık',
      'fw_exit_msg':
          'Oyundan çıkmak istediğine emin misin? İlerlemeniz kaybolacak.',

      // ── Games — True/False ──────────────────────────
      'tf_question_n': 'Soru {n}/{total}',
      'tf_points_info': 'Her doğru cevap 5 puandır',
      'tf_loading': 'Kelimeler yükleniyor...',
      'tf_is_correct': 'Bu çeviri doğru mu?',
      'tf_streak': '{n} Doğru Seri!',
      'tf_correct_msg': 'Doğru! 🎉',
      'tf_wrong_msg': 'Yanlış! 😔',
      'tf_correct_answer': 'Doğru cevap: {answer}',
      'tf_true': 'DOĞRU',
      'tf_false': 'YANLIŞ',
      'tf_perfect': 'Mükemmel!',
      'tf_great': 'Çok İyi!',
      'tf_good': 'İyi!',
      'tf_practice': 'Pratik Yap!',
      'tf_game_over': 'Oyun Bitti!',
      'tf_score': 'Puan',
      'tf_best_streak': 'En İyi Seri',
      'tf_level': 'Seviye',
      'tf_success': 'Başarı',
      'tf_exit_title': 'Oyundan Çık',
      'tf_exit_msg':
          'Oyundan çıkmak istediğine emin misin? İlerlemeniz kaybolacak.',

      // ── Games — Word Match ──────────────────────────
      'wm_title': 'Kelime Eşleştirmece',
      'wm_loading': 'Kelimeler yükleniyor...',
      'wm_memorize': 'Kelimeleri Ezberle!',
      'wm_study_cards': 'Kartları dikkatli incele',
      'wm_ready': 'Hazır mısın?',
      'wm_cards_closing': 'Kartlar kapanıyor...',
      'wm_english': 'İngilizce',
      'wm_turkish': 'Türkçe',
      'wm_perfect': 'Mükemmel!',
      'wm_great': 'Harika!',
      'wm_good': 'İyi!',
      'wm_keep_going': 'Devam Et!',
      'wm_game_complete': 'Oyun Tamamlandı!',
      'wm_total_score': 'Toplam Puan',
      'wm_time': 'Süre',
      'wm_correct_match': 'Doğru Eşleşme',
      'wm_wrong_attempt': 'Yanlış Deneme',
      'wm_success_rate': 'Başarı Oranı',
      'wm_exit_title': 'Çıkış',
      'wm_exit_msg': 'Oyundan çıkmak istediğine emin misin?',
    },

    // ═══════════════════  ENGLISH  ═══════════════════════════════════
    'en': {
      // ── Common ───────────────────────────────────────
      'app_name': 'Duck',
      'continue_btn': 'Continue',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'back': 'Go Back',
      'start': 'Start',
      'retry': 'Try Again',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'exit': 'Exit',
      'exit_btn': 'Exit',
      'correct': 'Correct',
      'wrong': 'Wrong',
      'score': 'Score',
      'time': 'Time',
      'level': 'Level',
      'success': 'Success',
      'lesson': 'Lesson',
      'completed': 'Completed',
      'play_again': 'Play Again',
      'main_menu': 'Main Menu',
      'continue_playing': 'Continue',
      'unknown_error': 'Unknown error',

      // ── Splash ───────────────────────────────────────
      'splash_hello': 'Hello',
      'splash_iam_duck': 'I\'m Duck',
      'splash_assistant': 'Your virtual English learning assistant',
      'splash_preparing': 'Preparing...',
      'splash_easy': 'Learning English with Duck is so easy',

      // ── Onboarding ──────────────────────────────────
      'onboard_hello': 'Hello! I\'m Duck 🦆',
      'onboard_assistant': 'Your virtual English assistant ✨',
      'onboard_ask_name': 'What should I call you?',
      'onboard_welcome': 'Welcome {name}!',
      'onboard_name_hint': 'Type your name...',
      'onboard_name_note': 'Duck will call you by this name.',
      'onboard_continue': 'Continue',
      'onboard_lets_start': 'Let\'s start then',
      'onboard_great_journey': 'We\'re starting a great journey!',
      'onboard_placement_test': 'Placement Test',
      'onboard_know_my_level': 'I Know My Level',

      // ── Select Level ────────────────────────────────
      'select_where': 'Where would you like to start?',
      'select_subtitle': 'Pick your level and start learning',
      'select_start': 'Let\'s go!',
      'select_pick': 'Pick a level',
      'level_beginner': 'Beginner',
      'level_beginner_desc': 'Basic words and simple sentences',
      'level_elementary': 'Elementary',
      'level_elementary_desc': 'Daily conversations and simple dialogues',
      'level_intermediate': 'Intermediate',
      'level_intermediate_desc': 'Fluent communication and detailed topics',
      'level_upper_intermediate': 'Upper Intermediate',
      'level_upper_intermediate_desc': 'Complex topics',
      'level_advanced': 'Advanced',
      'level_advanced_desc': 'Academic and professional level',

      // ── Home Screen ─────────────────────────────────
      'home_welcome': 'Welcome',
      'home_default_user': 'User',
      'home_learn_english': '🦆 Learn English',
      'home_daily_goals': 'Daily Goals',
      'home_quick_start': 'Quick Start',
      'home_pick_level': 'Pick Your Level',
      'home_25_lessons': '25 lessons per level',
      'home_25_lessons_short': '25 lessons',
      'home_beginner': 'Beginner',
      'home_beginner_desc': 'Basic words and sentences',
      'home_elementary': 'Elementary',
      'home_elementary_desc': 'Daily conversations',
      'home_intermediate': 'Intermediate',
      'home_intermediate_desc': 'Fluent communication',
      'home_upper_intermediate': 'Upper Int.',
      'home_upper_intermediate_desc': 'Complex topics',
      'home_advanced': 'Advanced',
      'home_advanced_desc': 'Professional level',
      'home_completed': 'Completed',
      'home_continue': 'Continue',
      'home_level_n': 'Level {level}',
      'home_lesson_n': 'Lesson {n}',
      'home_lesson_progress': '{completed} / 25 lessons · {percent}%',
      'home_continue_where': 'Continue where you left off',
      'home_level_lesson': 'Level {level} - Lesson {n}',
      'home_level_complete': 'Level {level} Completed! 🎉',
      'home_day_streak': 'Day Streak',
      'home_lessons': 'Lessons',
      'home_total_xp': 'Total XP',
      'home_vocabulary': 'Vocabulary',
      'home_vocabulary_desc': 'Learn new words',
      'home_listening': 'Listening',
      'home_listening_desc': 'Improve your ear',
      'home_mini_games': 'Mini Games',
      'home_fast_word': 'Fast Word',
      'home_fast_word_desc': 'Answer as fast as you can!',
      'home_true_false': 'True or False',
      'home_true_false_desc': 'Test your knowledge!',
      'home_word_match': 'Word Match',
      'home_word_match_desc': 'Learn with a memory game!',
      'home_daily_quests': 'Daily Quests',
      'home_weekly_quests': 'Weekly Quests',
      'home_quest_done': 'Completed!',
      'home_collect': 'Collect',
      'home_coming_soon': 'Coming Soon',
      'home_xp_earned': '🎉 +{xp} XP earned!',
      'home_xp_level_up': '🎉 +{xp} XP earned!\n🌟 Level Up!',
      'home_achievements': 'Achievements',
      'home_tab_learn': 'Learn',
      'home_tab_games': 'Games',
      'home_tab_quests': 'Quests',
      'home_tab_achievements': 'Achievements',
      'home_multiple_choice': 'Multiple Choice',
      'home_fill_blank': 'Fill in the Blank',
      'home_word_order': 'Word Order',
      'home_translation': 'Translation',
      'home_speaking': 'Speaking',
      'home_matching': 'Matching',
      'home_lesson_detail': '{level} · Lesson {n}',
      'home_lesson_done_msg': 'Completed ✅ You can redo it!',
      'home_lesson_start_msg': 'Complete this lesson and earn XP!',
      'home_activities': '{n} Activities',
      'home_redo': 'Redo',
      'home_start_lesson': 'Start Lesson',

      // ── Exercise Screen ─────────────────────────────
      'ex_multiple_choice': 'Multiple Choice',
      'ex_fill_blank': 'Fill in the Blank',
      'ex_word_order': 'Word Order',
      'ex_speaking': 'Speaking',
      'ex_translation': 'Translation',
      'ex_matching': 'Matching',
      'ex_exercise': 'Exercise',
      'ex_not_found': 'Lesson content not found (ID: {id})',
      'ex_preparing': 'Exercises are being prepared for this lesson.',
      'ex_load_error': 'Error loading exercises: {e}',
      'ex_great': 'Great!',
      'ex_great_desc': 'You completed a very successful lesson!',
      'ex_more_practice': 'A little more practice and you\'ll be perfect.',
      'ex_keep_going': 'Keep Going!',
      'ex_review_topic': 'Try reviewing the topic again.',
      'ex_try_again_improve': 'You can improve by trying again.',
      'ex_lesson_complete': 'Lesson Complete',
      'ex_success': 'Success',
      'ex_correct': 'Correct',
      'ex_wrong': 'Wrong',
      'ex_best_streak': 'Best Streak',
      'ex_review_needed': 'Review Needed',
      'ex_n_questions': '{n} questions',
      'ex_correct_answer': 'Correct answer:',
      'ex_continue': 'CONTINUE',
      'ex_loading': 'Preparing exercises...',
      'ex_back': 'Go Back',
      'ex_results': 'Results',
      'ex_quit_title': 'Do you want to quit?',
      'ex_quit_message': 'Your progress won\'t be saved.',
      'ex_streak_2': 'Two in a row! 🔥',
      'ex_streak_3': 'Three in a row! 🔥🔥',
      'ex_streak_4': 'Super streak! 🔥🔥🔥',
      'ex_perfect': 'Perfect! 🎉',
      'ex_awesome': 'Awesome! 🎉',
      'ex_correct_answer_msg': 'Correct answer!',
      'ex_wrong_answer_msg': 'Wrong answer 😕',
      'ex_wrong_feedback': 'You can try again or see the correct answer.',
      'ex_retry': 'Try Again',
      'ex_show_answer': 'Show Answer',
      'ex_unknown_type': 'Unknown exercise type: {type}',
      'ex_render_error': 'Error displaying exercise',
      'ex_magnificent': 'Magnificent!',
      'ex_near_perfect': 'Near perfect performance!',
      'ex_doing_well': 'Doing Well!',
      'ex_dont_give_up': 'Don\'t Give Up!',
      'ex_unstoppable': 'Unstoppable! ⚡',
      'ex_match_progress': '{matched} / {total} matched',
      'ex_match_hint': 'Select one card from each side',
      'ex_translate_hint': 'Type your translation...',
      'ex_speak_hint': 'Press the mic to speak',

      // ── Placement Test ──────────────────────────────
      'pt_title': 'Placement Test',
      'pt_subtitle': 'Let\'s determine your English level',
      'pt_50_questions': '50 Questions',
      'pt_50_desc': 'Questions at different difficulty levels',
      'pt_30_min': '30 Minutes',
      'pt_determine': 'Level Assessment',
      'pt_start': 'Start Test',
      'pt_back': 'Go Back',
      'pt_select_error': 'Could not select test questions',
      'pt_load_error': 'Error loading questions: {e}',
      'pt_loading': 'Preparing Questions...',
      'pt_load_fail': 'Could Not Load Questions',
      'pt_retry': 'Try Again',
      'pt_question_n': 'Question {n}',
      'pt_answered': '{n} answered',
      'pt_points': '{n} points',
      'pt_finish': 'Finish Test',
      'pt_next': 'Next',
      'pt_congrats': 'Congratulations!',
      'pt_complete': 'Your placement test is complete',
      'pt_total_score': 'Total Score',
      'pt_correct_answers': 'Correct Answers',
      'pt_success_rate': 'Success Rate',
      'pt_your_level': 'Your Level: {level}',
      'pt_exit_title': 'Exit Test',
      'pt_exit_msg': 'If you leave, all progress will be lost. Are you sure?',
      'pt_beginner': 'Beginner Level',
      'pt_elementary': 'Elementary Level',
      'pt_intermediate': 'Intermediate Level',
      'pt_upper_intermediate': 'Upper Intermediate Level',
      'pt_advanced': 'Advanced Level',
      'pt_test': 'Level Test',
      'pt_questions_fail': 'Could not load questions',
      'pt_previous': 'Previous',
      'pt_elapsed': 'Elapsed Time',
      'pt_max_time': 'Maximum time limit',
      'pt_assessment_desc': 'Assessment from A1 to C1',

      // ── Learning Path ───────────────────────────────
      'lp_title': 'Learning Path',
      'lp_subtitle': 'Improve your level',
      'lp_active_level': 'Active Level',
      'lp_level_status': 'Level Status',
      'lp_completed': 'Completed',
      'lp_completed_check': 'Completed ✓',
      'lp_lesson_progress': 'Lesson {p} / {total}',
      'lp_level_progress': '{level} · Completed',
      'lp_level_in_progress': '{level} · Lesson {p} / {total}',
      'lp_level_n': 'Level {level}',
      'lp_lessons_status': '{total} lessons · {status}',
      'lp_lesson_n': 'Lesson {n}',
      'lp_close': 'Close',
      'lp_redo': 'Redo',
      'lp_start': 'Start',
      'lp_congrats': '🎉 Congratulations! 🎉',
      'lp_level_done': 'You successfully completed the {level} level!',
      'lp_next_level': 'You moved on to the next level!',
      'lp_next_lesson': 'Lesson 1 / {total} is waiting for you',
      'lp_all_done': 'You completed all levels! You\'re now in expert mode.',
      'lp_go_next': 'Go to the next level',
      'lp_awesome': 'Awesome!',
      'lp_locked': 'Locked',
      'lp_locked_emoji': 'Locked 🔒',

      // ── Vocabulary ──────────────────────────────────
      'vocab_title': 'Learn Words',
      'vocab_level': 'Level: {level}',
      'vocab_tap_hint': 'Tap to go to the next word',
      'vocab_learn_desc': 'Learn English - Turkish words',
      'vocab_start': 'Start',
      'vocab_turkish': '🇹🇷 Turkish',
      'vocab_next_hint': 'Tap for next word',

      // ── Settings ────────────────────────────────────
      'settings_title': 'Settings',
      'settings_preferences': 'Preferences',
      'settings_appearance': 'Appearance',
      'settings_language': 'Language',
      'settings_about': 'About',
      'settings_notifications': 'Notifications',
      'settings_notifications_desc': 'Reminders and updates',
      'settings_vibration': 'Vibration',
      'settings_vibration_desc': 'Haptic feedback',
      'settings_theme': 'Theme',
      'settings_theme_light': 'Light',
      'settings_theme_dark': 'Dark',
      'settings_app_language': 'App Language',
      'settings_premium': 'Premium Member',
      'settings_name_changes': 'Name changes: {n}/2 remaining',
      'settings_edit_name': 'Edit Name',
      'settings_new_name_hint': 'Enter your new name',
      'settings_name_changes_left': '{n} changes remaining',
      'settings_name_updated': 'Your name has been updated to "{name}"!',
      'settings_name_limit': 'No name changes remaining this month.',
      'settings_logout': 'Log Out',
      'settings_logout_msg':
          'Are you sure you want to log out? All your data will be deleted.',
      'settings_developer': 'Developer',
      'settings_app_desc': 'English Learning App',
      'settings_terms': 'Terms of Service',
      'settings_privacy': 'Privacy Policy',
      'settings_kvkk': 'Data Protection Notice',
      'settings_licenses': 'Open Source Licenses',
      'settings_last_update': 'Last updated: January 1, 2025',

      // ── Games — Fast Word ───────────────────────────
      'fw_question_n': 'Question {n}/{total}',
      'fw_loading': 'Preparing Fast Word game...',
      'fw_instruction': 'Find the correct answer as fast as you can!',
      'fw_correct': 'Correct',
      'fw_wrong': 'Wrong',
      'fw_time': 'Time',
      'fw_perfect': 'Perfect!',
      'fw_great': 'Great!',
      'fw_good': 'Good!',
      'fw_practice': 'Practice!',
      'fw_game_over': 'Fast Word - Game Over!',
      'fw_total_score': 'TOTAL SCORE',
      'fw_fast_tip': 'Faster answers earn more points!',
      'fw_success': 'Success',
      'fw_level': 'Level',
      'fw_exit_title': 'Exit Game',
      'fw_exit_msg':
          'Are you sure you want to exit? Your progress will be lost.',

      // ── Games — True/False ──────────────────────────
      'tf_question_n': 'Question {n}/{total}',
      'tf_points_info': 'Each correct answer is worth 5 points',
      'tf_loading': 'Loading words...',
      'tf_is_correct': 'Is this translation correct?',
      'tf_streak': '{n} Correct Streak!',
      'tf_correct_msg': 'Correct! 🎉',
      'tf_wrong_msg': 'Wrong! 😔',
      'tf_correct_answer': 'Correct answer: {answer}',
      'tf_true': 'TRUE',
      'tf_false': 'FALSE',
      'tf_perfect': 'Perfect!',
      'tf_great': 'Great!',
      'tf_good': 'Good!',
      'tf_practice': 'Practice!',
      'tf_game_over': 'Game Over!',
      'tf_score': 'Score',
      'tf_best_streak': 'Best Streak',
      'tf_level': 'Level',
      'tf_success': 'Success',
      'tf_exit_title': 'Exit Game',
      'tf_exit_msg':
          'Are you sure you want to exit? Your progress will be lost.',

      // ── Games — Word Match ──────────────────────────
      'wm_title': 'Word Match',
      'wm_loading': 'Loading words...',
      'wm_memorize': 'Memorize the Words!',
      'wm_study_cards': 'Study the cards carefully',
      'wm_ready': 'Ready?',
      'wm_cards_closing': 'Cards are closing...',
      'wm_english': 'English',
      'wm_turkish': 'Turkish',
      'wm_perfect': 'Perfect!',
      'wm_great': 'Great!',
      'wm_good': 'Good!',
      'wm_keep_going': 'Keep Going!',
      'wm_game_complete': 'Game Complete!',
      'wm_total_score': 'Total Score',
      'wm_time': 'Time',
      'wm_correct_match': 'Correct Match',
      'wm_wrong_attempt': 'Wrong Attempt',
      'wm_success_rate': 'Success Rate',
      'wm_exit_title': 'Exit',
      'wm_exit_msg': 'Are you sure you want to exit the game?',
    },
  };
}
